Fix missing check in sync triggers
Check if `pk_set` is a True-like (e.g. non-empty set) object.

The `pk_set` parameter may be `None` in cases when user teams list is
cleared (e.g. calling `user.teams.clear()`).

This code will fail with the following exception:

```
TypeError: 'NoneType' object is not iterable
```

due to attempt to iterate over `None` value.